// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8CkoOnNNGzIRQXcUxk5P-FVEmK73XwNs',
    appId: '1:444858710838:web:17cec4e4937448a898d197',
    messagingSenderId: '444858710838',
    projectId: 'somoa-8dea6',
    authDomain: 'somoa-8dea6.firebaseapp.com',
    storageBucket: 'somoa-8dea6.appspot.com',
    measurementId: 'G-DVRPR1PBCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqD4ZF5ovalI556NzDFm6mFNENcMda2qw',
    appId: '1:444858710838:android:3771661054b5d35498d197',
    messagingSenderId: '444858710838',
    projectId: 'somoa-8dea6',
    storageBucket: 'somoa-8dea6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9J9xeibjvivgfcr4K1UwgogpkcAW6aAg',
    appId: '1:444858710838:ios:bd0dc0881667922b98d197',
    messagingSenderId: '444858710838',
    projectId: 'somoa-8dea6',
    storageBucket: 'somoa-8dea6.appspot.com',
    iosBundleId: 'com.example.somoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9J9xeibjvivgfcr4K1UwgogpkcAW6aAg',
    appId: '1:444858710838:ios:b8ca9afc576d550b98d197',
    messagingSenderId: '444858710838',
    projectId: 'somoa-8dea6',
    storageBucket: 'somoa-8dea6.appspot.com',
    iosBundleId: 'com.example.somoa.RunnerTests',
  );
}
